### ISSUE TITLE
Absolute urls

### ISSUE THREAD

**Issue by beaulm** [clearhead/gulp-clearbuild#7]
If it's not too much work, it would be great to have an option where the NPI would rewrite absolute url's to relative ones so you could navigate some sites locally that you can't currently.

For instance [P&G](http://www.pgshop.com/) has their links specify the FQDN like http://www.pgshop.com/pgshop-brand-tide/. It would be great to have those urls rewritten to [/pgshop-brand-tide/]() on the fly.

**Comment by tomfuertes** [comment]
+1 - I think this is more ripping out code than leaving in. Migrating to NPI though
